name: PyPI-Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build and run build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools build wheel --upgrade
          python -m build --sdist .

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
          print-hash: true
